export * from "./Home";
export * from "./Search";
export * from "./ProductDetails";
export * from "./Discussion";
export * from "./Profile";
export * from "./Cart";
export * from "./Category";
export * from "./Stylist";
export * from "./Profile";
export * from './Register'
export * from './DiscussionDetails';
